[package]
name = "advent2024"
version = "0.1.0"
rust-version = "1.83.0"
edition = "2021"
authors = ["efhd"]

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
nom = "7.1.3"
util = { path = "../util" }
